### ISSUE TITLE
How to recovery?

### ISSUE THREAD

**Issue by kfuru** [ossc-db/pg_rman#29] opened 2016-06-24 02:58 UTC
Hi, I'm testing in 9.6beta1.
If the file under $PGDATA has been deleted, how do you recover?

Example:
1. stop PostgreSQL.
2. clear $PGDATA directory. (including 'pg_control' file)
3. restore using pg_rman
   $ pg_rman restore
   pg_rman: could not open file "/var/lib/pgsql/9.6/data/global/pg_control" for reading: No such file or directory
   $ (terminated)
 

13/Apr/2016 older version (eg. hash number: 8d37a9c) is ok.
  $ pg_rman restore
  WARNING: could not open pg_controldata file "/var/lib/pgsql/9.6/data/global/pg_control": No such file or directory
  WARNING: could not open pg_controldata file "/var/lib/pgsql/9.6/data/global/pg_control": No such file or directory
  INFO: the recovery target timeline ID is not given
  INFO: use timeline ID of latest full backup as recovery target: 3
  INFO: calculating timeline branches to be used to recovery target point
  INFO: searching latest full backup which can be used as restore start point
   :
   :

Am I something missing?

**Comment by amitlan** [comment] 2016-06-24 10:11
I think that is happening because of commit 14507e3b0c373cc88ad64b7b74a2436d847f67dc

Since that commit, we use `get_controlfile()` function provided by PostgreSQL, so the behavior has changed.  Maybe, we should consider if that is undesirable change of behavior.  I think it's OK.

But we can avoid that by not deleting files under $PGDATA by ourselves.  `pg_rman restore` automatically deletes them for us.

**Comment by bwtakacy** [comment] 2016-06-26 02:19
Thanks @kfuru for reporting.

As amit said, this behavior change seems to be caused by PostgreSQL API change.

We have already noted in doc as 
```In addition, do not erase a original database cluster, because pg_rman has to check the timeline ID or data checksum status from it. ```
but this may be easy to overlook.

Is it better to modify the doc with much more warning?

**Comment by amitlan** [comment] 2016-06-27 04:46
@bwtakacy Agree about putting that line as a WARNING note.

**Comment by kfuru** [comment] 2016-06-27 05:58
Do not manually remove the under $PGDATA is ok.
In Test, I removed under the $PGDATA intentionally manually.

In failure or something trouble, it is thinking that PGDATA is lost.
How to recover in such a case I was allowed to question.

**Comment by amitlan** [comment] 2016-06-27 06:23
So it seems Furutani-san's question is: If data under `PGDATA` is lost because of some other reason (no manual removal), can pg_rman be used to recover?  Due to changed behavior, it would be impossible to recover. Isn't that correct?

That sounds like a valid concern.  Should we consider reverting the following commit(s)?

master: 14507e3b0c373cc88ad64b7b74a2436d847f67dc (use get_controlfile API)
9.5: 606dda9caddbc63eb285b96dfb632a82a7d11e82 (treat failure to open or read from control file as ERROR.)
9.4: 3dd75802d5d15f4a9bafd9996e35cd5bf233016b (treat failure to open or read from control file as ERROR.)
9.3: 8c1ac413dc34cca35a8c7eb67855e38f060e50c8 (treat failure to open or read from control file as ERROR.)
9.2: 0cc3e1b5cf8530182c66efd9acb256d67bc69080 (treat failure to open or read from control file as ERROR.)
pre-9.2: 4b012ced8aa795181d11982c7ba79790a54a90bc (treat failure to open or read from control file as ERROR.)

Thoughts?

**Comment by bwtakacy** [comment] 2016-06-29 01:13
Hmm.

How about  adding  some verification of the existence of pg_control?
Thinking about maintain pg_rman for PostgreSQL major version up, I feel it is not good to keep custom api inside pg_rman but better to use PostgreSQL side API.

**Comment by amitlan** [comment] 2016-06-29 01:24
Good suggestion.

How about just stat() control file path?  If exists, proceed with get_controlfile().

However, that's just in the master branch.  In older branches, I think it may be OK to revert to warnings.

Thoughts?

**Comment by amitlan** [comment] 2016-06-29 02:36
How about 93de0f8b2e50ad95ab56278178c56e15d52127d2 ?

Made changes only for `do_restore()` path as doing the same for `do_init()` and `do_backup()` does not make much sense.

Thoughts?

**Comment by bwtakacy** [comment] 2016-06-29 04:12
Looks nice :+1: 
Agree about reverting in older branches.

About `do_init()` and `do_backup()`, I think it is better to do similar way, too.
Because the `get_controlfile()` suddenly exits and does not show a user friendly error messages, users may be lost how to resolve.

**Comment by amitlan** [comment] 2016-06-29 05:34
Thanks for taking a look!  I will go revert in older branches.

About `init` and `backup`, I thought that there is not much point in issuing a warning and going ahead. What could those commands do with such a data directory?

As for `restore`, we have backups to restore and can proceed (possibly) reasonably without needing to read the controlfile.

Thoughts?

**Comment by bwtakacy** [comment] 2016-06-29 06:55
Thanks for surveying:)
>Or do you mean that we should not let get_controlfile() output the message? That is, use the similar method (and hence message), but issue ERROR instead of WARNING.

No, that's too difficult for this issue, i think.

The error message shown by `get_controlfile()` in `init` and `backup` seems to be enough for me.
Now, I totally agree with this fix.

How about you, @kfuru?

**Comment by kfuru** [comment] 2016-06-30 08:22
I confirmed this correction, and think this is enough.
It is thought that there are many users assuming recovery from data disappearance like me.
Thank you for corresponding.

**Comment by amitlan** [comment] 2016-06-30 08:27
Thank you, closing this issue.

**Closed by amitlan** 2016-06-30 08:27 UTC
