### ISSUE TITLE
pg_rman hangs when using compress-data

### ISSUE THREAD

**Issue by meiemik** [ossc-db/pg_rman#74] opened 2018-07-29 16:13 UTC
pg_rman is working fine if used normally and finishes full backup within 4-5min (Test Environment). But when adding the --compress-data option (which we would like to use), it just stops (hangs)  and after 2-3hours of waiting, I have to [Crtl+c] the program which will end with an ERROR in pg_rman show and therefore unusable.
Command: pg_rman backup --backup-mode=full --compress-data
OS: CentOS 7.4 (64bit)
PostGreSQL: postgresql10-10.2.1PGDG.rhel7.x86-64.rpm (as well as server libs contrib and devel)
PG_Rman: pg_rman-1.3.6-1.pg10.rhel7.x86_64.rpm (NOT recompiled)
A cause might be that currently some tablespaces are still empty (no files to compress).
By the way, I was able to successfully backup archive (only) in compress-data mode.

**Comment by MoonInsung** [comment] 2021-06-17 07:33
Dear @meiemik .

Is it possible to reproduce it in the current state? 
Unfortunately, I can't figure out the cause of this issue because it's not reproduced.

And I apologize for this comment. 
This issue is very old, so if you don't have any opinion, 
I'll close the issue around June 28th(JST).
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.

**Closed** 2021-06-28 00:31 UTC
Labels: help wanted, pending close
