### ISSUE TITLE
Restore fails if the mount directory exists

### ISSUE THREAD

**Issue by ester41** [ossc-db/pg_rman#113] opened 2019-06-17 01:43 UTC
Hi.

If the mount directory exists in the restore target, folder deletion for restore processing fails.

PostgreSQL Version: 11.2
pg_rman Version: 1.3.8

```
# /usr/pgsql-11/bin/pg_rman --verbose restore
========================================
restore start
INFO: the recovery target timeline ID is not given
INFO: use timeline ID of current database cluster as recovery target: 1
INFO: calculating timeline branches to be used to recovery target point
INFO: searching latest full backup which can be used as restore start point
INFO: found the full backup can be used as base in recovery: "2019-06-11 09:31:49"
----------------------------------------
INFO: copying online WAL files and server log files
copy "000000010000000000000002"
copy "000000010000000000000003"
create directory "archive_status"
copy "pg_statsinfo.log"
copy "postgresql.20190617102358.csv"
copy "postgresql.20190617102358.log"
copy "postgresql.20190617102358.log.copy"
copy "postgresql.20190617102415.csv"
copy "postgresql.20190617102415.log"
----------------------------------------
INFO: clearing restore destination
ERROR: could not remove directory "/var/lib/pgsql/11/data/../pg_wal": Device or resource busy
#
```

**Comment by jakjohnson** [comment] 2019-09-27 12:41
I am also having this issue with a device that is mounted on $PGDATA/pg_xlog.

**Comment by MoonInsung** [comment] 2019-10-18 02:48
Dear ester41.

Sorry for late answer.
I have a lot of thinking about this problem...
I think the problem was caused by the policy of the OS rather than the pg_rman.

When recovery is executed, pg_rman deletes the existing pgdata file.
Therefore, it tries to delete the mounted directory(pg_wal), but it seems to be a problem that could don't be deleted due to OS policy.

Sorry for not helping a lot...
Also, I'll update the manual related to mount directory.

Best regards.
Moon.

**Comment by MoonInsung** [comment] 2021-06-17 07:55
Dear ester41.

And I apologize for this comment. 
This issue is very old, so if you don't have any opinion, 
I'll close the issue around June 28th(JST).
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.

**Closed** 2021-06-28 00:32 UTC
Labels: pending close
