### ISSUE TITLE
ERROR: switched WAL could not be archived in 10 seconds

### ISSUE THREAD

**Issue by lzhmhznr** [ossc-db/pg_rman#104] opened 2019-01-08 07:27 UTC
```
1 : gedit postgresql.conf	 	 
$PGDATA/postgresql.conf	 
archive_mode = on
archive_command = 'test ! -f /mnt/server/archivedir/%f && cp %p /mnt/server/archivedir/%f'
archive_timeout = 10
	 
2 : pg_rman  init
/opt/pg_rman/pg_rman  init --backup-path=/home/backup/postgresql/11
INFO: ARCLOG_PATH is set to '/opt/pg_rman/arclog'
INFO: SRVLOG_PATH is set to '/home/data/postgresql/11/pg_log'	 

3 : make installcheck
postgres@master-1:/opt/pg_rman$ make installcheck
============== running regression test queries ==============
test init                         ... ok
test option                       ... ok
test show                         ... ok
test delete                       ... ok
test purge                        ... ok
test backup                       ... ok
test backup_management            ... ok
test restore                      ... ok
test restore_checksum             ... ok
test backup_from_standby          ... ok
test arc_srv_log_management       ... ok

======================
 All 11 tests passed. 
======================

4 : backup : return error
postgres@master-1:/opt/pg_rman$ /opt/pg_rman/pg_rman backup --backup-mode=full
INFO: copying database files
ERROR: switched WAL could not be archived in 10 seconds


```

**Comment by huangfumingyue** [comment] 2019-01-09 02:22
Hi,
Can you check the output with verbose or debug options?

**Comment by lzhmhznr** [comment] 2019-01-09 03:33
How can i check the output with verbose or debug options?

**Comment by richard2017** [comment] 2019-01-09 06:31
DEBUG: the initially configured target database : SYSTEM_IDENTIFIER = 6639236161517687881
DEBUG: the system identifier of current target database : 6639236161517687881
DEBUG: the backup target database is the same as initial configured one.
DEBUG: destination directories of backup are initialized
DEBUG: checking PostgreSQL server version
DEBUG: server version is 10.0.6
DEBUG: checking block size setting
DEBUG: (query) SELECT current_setting($1)
DEBUG:  (param:0) = block_size
DEBUG: block size is 8192
DEBUG: checking block size setting
DEBUG: (query) SELECT current_setting($1)
DEBUG:  (param:0) = wal_block_size
DEBUG: wal block size is 8192
DEBUG: data checksum disabled on the initially configured database
INFO: copying database files
DEBUG: executing pg_start_backup()
DEBUG: (query) SELECT * from pg_walfile_name_offset(pg_start_backup($1, $2, $3))
DEBUG:  (param:0) = 2019-01-09 14:28:02 with pg_rman
DEBUG:  (param:1) = true
DEBUG:  (param:2) = false
DEBUG: backup start point is (WAL file: 000000010000000600000000, xrecoff: 96)
DEBUG: (query) SELECT * FROM pg_last_wal_replay_lsn()
DEBUG: (query) SELECT * FROM pg_last_wal_replay_lsn()
DEBUG: (query) SELECT * FROM pg_last_wal_replay_lsn()
DEBUG: (query) SELECT * FROM pg_last_wal_replay_lsn()
DEBUG: (query) SELECT * FROM pg_last_wal_replay_lsn()
DEBUG: (query) SELECT * FROM pg_last_wal_replay_lsn()
DEBUG: (query) CHECKPOINT
DEBUG: taking full backup of database files
Processed 980 of 980 files, skipped 0
DEBUG: executing pg_stop_backup()
DEBUG: (query) SET client_min_messages = warning;
DEBUG: (query) SELECT * FROM pg_stop_backup($1)
DEBUG:  (param:0) = false
DEBUG: (query) SELECT * FROM pg_walfile_name_offset($1)
DEBUG:  (param:0) = 6/168
DEBUG: backup end point is (WAL file: 000000010000000600000000, xrecoff: 360)
DEBUG: waiting for 000000010000000600000000 is archived
DEBUG: (query) SELECT txid_current();
DEBUG: current XID is 560
ERROR: switched WAL could not be archived in 10 seconds
DEBUG: update bakckup status from RUNNING to ERROR

**Comment by lzhmhznr** [comment] 2019-01-09 07:15
postgres@master-1:/opt/pg_rman$ /opt/pg_rman/pg_rman backup --backup-mode=full --with-serverlog  --debug
DEBUG: the initially configured target database : SYSTEM_IDENTIFIER = 6639202594043046705
DEBUG: the system identifier of current target database : 6639202594043046705
DEBUG: the backup target database is the same as initial configured one.
DEBUG: destination directories of backup are initialized
DEBUG: checking PostgreSQL server version
DEBUG: server version is 11.0.1
DEBUG: checking block size setting
DEBUG: (query) SELECT current_setting($1)
DEBUG: 	(param:0) = block_size
DEBUG: block size is 8192
DEBUG: checking block size setting
DEBUG: (query) SELECT current_setting($1)
DEBUG: 	(param:0) = wal_block_size
DEBUG: wal block size is 8192
DEBUG: data checksum disabled on the initially configured database
INFO: copying database files
DEBUG: executing pg_start_backup()
DEBUG: (query) SELECT * from pg_walfile_name_offset(pg_start_backup($1, $2, $3))
DEBUG: 	(param:0) = 2019-01-09 15:13:01 with pg_rman
DEBUG: 	(param:1) = true
DEBUG: 	(param:2) = false
DEBUG: backup start point is (WAL file: 000000010000000000000018, xrecoff: 40)
DEBUG: taking full backup of database files
DEBUG: executing pg_stop_backup()
DEBUG: (query) SET client_min_messages = warning;
DEBUG: (query) SELECT * FROM pg_stop_backup($1)
DEBUG: 	(param:0) = false
DEBUG: (query) SELECT * FROM pg_walfile_name_offset($1)
DEBUG: 	(param:0) = 0/180000F8
DEBUG: backup end point is (WAL file: 000000010000000000000018, xrecoff: 248)
DEBUG: waiting for 000000010000000000000018 is archived
DEBUG: (query) SELECT txid_current();
DEBUG: current XID is 692
ERROR: switched WAL could not be archived in 10 seconds
DEBUG: update bakckup status from RUNNING to ERROR

**Comment by amitlan** [comment] 2019-01-10 02:34
Hi,

Archive directory is `/mnt/server/archivedir`  according to archive_command setting in postgresql.conf.

```
$PGDATA/postgresql.conf	 
archive_command = 'test ! -f /mnt/server/archivedir/%f && cp %p /mnt/server/archivedir/%f'
```

But pg_rman thinks it is `/opt/pg_rman/arclog`, based on this:

```
/opt/pg_rman/pg_rman  init --backup-path=/home/backup/postgresql/11
INFO: ARCLOG_PATH is set to '/opt/pg_rman/arclog'
INFO: SRVLOG_PATH is set to '/home/data/postgresql/11/pg_log'	
```

Where is pg_rman getting that value from?  What value of PGDATA is pg_rman using?

The error seems to be occurring because pg_rman won't be able to find the archived WAL files under `/opt/pg_rman/arclog`, if they're really archived under `/mnt/server/archivedir` by archive command.

**Comment by MoonInsung** [comment] 2021-06-17 07:46
Dear @lzhmhznr 

The issue is caused by timing or environment.
For example, 

 1. Caused by timing
the *.done was deleted by the CHECKPOINT just before pg_rman checked that the archive was complete.

2. Caused by enviroment
This is a problem with the hardware lack or configuration of the archive_command.

If this issue is caused by timing, try backing up again.

And I apologize for this comment. 
This issue is very old, so if you don't have any opinion, I'll close the issue around June 28th.
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.

**Closed** 2021-06-28 00:31 UTC
Labels: pending close, question
