### ISSUE TITLE
conflicting types for ‘figure_out_segno’	pg12.1	D:\VS2017\LinuxProject\pg12.1\data.c	1261

### ISSUE THREAD

**Issue by qzren1982** [ossc-db/pg_rman#130] opened 2019-12-31 07:14 UTC
conflicting types for ‘figure_out_segno’	pg12.1	D:\VS2017\LinuxProject\pg12.1\data.c	1261

编译的时候报这个错误。看了一下代码。没发现问题。pg版本是12.1

把这段代码注释掉才行：

if (data_checksum_enabled)
                segno = figure_out_segno(file->path);   -- 注释掉这段才行
else
                segno = 0;

**Comment by qzren1982** [comment] 2019-12-31 07:41
OS: CENTOS6.9
gcc version:4.4.7

**Comment by huangfumingyue** [comment] 2020-01-22 02:27
你好，
我想请问一下，你是从Branch ⇒　REL_12_STABLE下载的代码吗？
PS：如果可以的话，最好是用英语回复。

**Comment by MoonInsung** [comment] 2021-06-17 08:15
Dear @qzren1982 

I don't know Chinese, so I don't know what the problem is... 
Please write English.

And I apologize for this comment. 
This issue is very old, so if you don't have any opinion, I'll close the issue around June 28th.
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.

**Closed** 2021-06-28 00:32 UTC
Labels: pending close
